# Generated by Django 4.2 on 2023-11-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_classroom_topic_alter_customuser_role_test_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.mentor'),
        ),
    ]
