# Generated by Django 4.2 on 2023-11-16 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_classroom_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='host',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
