# Generated by Django 4.2 on 2023-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_remove_test_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit_per_question',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
