# Generated by Django 5.0.2 on 2024-04-07 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_testattempt_testattemptquestion_testscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit_per_question',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testscore_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
