# Generated by Django 5.0.2 on 2024-04-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_test_time_limit_per_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit_per_question',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
